name: Comment Terraform Plan on PR

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    terraform:
        name: "Terraform CDK Diff"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"

            - name: Install cdktf
              run: npm install -g cdktf-cli

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.4.6

            - name: Install dependencies
              run: npm ci

            - name: Generate bindings for providers and modules
              run: cdktf get

            - name: Run unit tests
              run: npm test

            - name: Generate Terraform plan
              id: plan
              run: npm run deploy:plan
              continue-on-error: true

            - uses: actions/github-script@v5
              if: github.event_name == 'pull_request'
              env:
                  PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
                      <details><summary>Show Plan</summary>
                      \`\`\`${process.env.PLAN}\`\`\`
                      </details>
                      *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: output
                      })
